name: Ou's Friends

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./
        cname: links.slirv.vip
        user_name: slivermoe
        user_email: 148861329+slivermoe@users.noreply.github.com
      